import path from "node:path";
import { writeFile, pathExists } from "../util/fs.js";
import { runSafe } from "../util/exec.js";
import type { PmCommands } from "../detect/packageManager.js";
import type { FrameworkInfo } from "../detect/framework.js";
import type { GeneratedFiles } from "../generate/msw.js";
import { injectVite } from "./framework-vite.js";
import { injectNext } from "./framework-next.js";
import { injectAstro } from "./framework-astro.js";
import { injectGeneric } from "./generic.js";

export interface InjectResult {
  mocksDir: string;
  editedEntry: string;
  workerInstalled: boolean;
}

/**
 * Write the generated MSW files into the worktree, ensure msw + the service
 * worker script are present, and wire the bootstrap into the app entry.
 */
export async function injectMocks(opts: {
  appDir: string;
  framework: FrameworkInfo;
  pm: PmCommands;
  files: GeneratedFiles;
  onLine?: (line: string) => void;
}): Promise<InjectResult> {
  const { appDir, framework, pm, files } = opts;
  const mocksDirRel = "mocks";
  const mocksDir = path.join(appDir, mocksDirRel);

  // 1. Write the mock modules.
  await writeFile(path.join(mocksDir, "handlers.ts"), files.handlersTs);
  await writeFile(path.join(mocksDir, "browser.ts"), files.browserTs);
  await writeFile(path.join(mocksDir, "start.ts"), files.bootstrapTs);
  const hasAuthSeed = !!files.authSeedTs;
  if (files.authSeedTs) {
    await writeFile(path.join(mocksDir, "auth-seed.ts"), files.authSeedTs);
  }
  await writeFile(path.join(mocksDir, "auto.ts"), autoStartSource(hasAuthSeed));

  // 2. Ensure msw is installed in the worktree.
  let workerInstalled = false;
  if (!(await hasMsw(appDir))) {
    const add = pm.addDev(["msw"]);
    const res = await runSafe(add.command, add.args, { cwd: appDir });
    if (res.exitCode !== 0) {
      opts.onLine?.(`Warning: failed to add msw (${res.stderr.split("\n").slice(-3).join(" ")})`);
    }
  }

  // 3. Drop the service worker into the public dir via `msw init`.
  const publicDir = framework.publicDir;
  const init = pm.exec("msw", ["init", publicDir, "--save"]);
  const initRes = await runSafe(init.command, init.args, { cwd: appDir });
  workerInstalled =
    initRes.exitCode === 0 ||
    (await pathExists(path.join(appDir, publicDir, "mockServiceWorker.js")));
  if (!workerInstalled) {
    opts.onLine?.(
      `Warning: 'msw init' did not produce ${publicDir}/mockServiceWorker.js — mocks may not load.`,
    );
  }

  // 4. Wire the bootstrap into the framework entry.
  const editedEntry = await injectByFramework(framework, appDir, mocksDirRel);

  return { mocksDir, editedEntry, workerInstalled };
}

async function injectByFramework(
  framework: FrameworkInfo,
  appDir: string,
  mocksDirRel: string,
): Promise<string> {
  switch (framework.name) {
    case "vite":
    case "sveltekit":
      return injectVite(appDir, mocksDirRel);
    case "next":
      return injectNext(appDir, mocksDirRel);
    case "astro":
      return injectAstro(appDir, mocksDirRel);
    case "cra":
    case "remix":
    case "unknown":
    default:
      // CRA/Remix/unknown: try HTML injection, fall back to generic.
      try {
        return await injectVite(appDir, mocksDirRel);
      } catch {
        return injectGeneric(appDir, mocksDirRel);
      }
  }
}

async function hasMsw(appDir: string): Promise<boolean> {
  return pathExists(path.join(appDir, "node_modules", "msw", "package.json"));
}

function autoStartSource(hasAuthSeed: boolean): string {
  // The auth seed is a synchronous side-effecting import, placed first so it
  // writes the fake session to localStorage before the app's auth SDK (loaded
  // by a later module script) reads it.
  const seedImport = hasAuthSeed ? `import "./auth-seed";\n` : "";
  return `/* eslint-disable */
// Generated by sauce-code. Auto-starts mocks when loaded as a module script.
${seedImport}import { startMocks } from "./start";
await startMocks();
`;
}
