import { isJsonContentType } from "../util/url.js";
import type { MockRoute } from "../capture/types.js";

export interface GeneratedFiles {
  handlersTs: string;
  browserTs: string;
  bootstrapTs: string;
}

/** MSW http method helpers we emit. */
const METHOD_MAP: Record<string, string> = {
  GET: "get",
  POST: "post",
  PUT: "put",
  PATCH: "patch",
  DELETE: "delete",
  HEAD: "head",
  OPTIONS: "options",
};

/** Render the MSW handler module + browser worker + bootstrap. */
export function generateMswFiles(routes: MockRoute[]): GeneratedFiles {
  const handlers = routes
    .map((r, i) => renderHandler(r, i))
    .filter(Boolean)
    .join(",\n\n");

  const needsBase64Helper = routes.some((r) => r.bodyEncoding === "base64");
  const needsQueryHelper = routes.some((r) => r.variants && r.variants.length > 1);

  const helpers = [
    needsBase64Helper ? base64Helper : "",
    needsQueryHelper ? stableQueryHelper : "",
  ]
    .filter(Boolean)
    .join("\n");

  const handlersTs = `/* eslint-disable */
// Generated by sauce-code. Do not edit by hand — re-run sauce-code to refresh.
import { http, HttpResponse } from "msw";
${helpers}
export const handlers = [
${handlers}
];
`;

  const browserTs = `/* eslint-disable */
// Generated by sauce-code.
import { setupWorker } from "msw/browser";
import { handlers } from "./handlers";

export const worker = setupWorker(...handlers);
`;

  const bootstrapTs = bootstrapModule;

  return { handlersTs, browserTs, bootstrapTs };
}

function renderHandler(route: MockRoute, index: number): string {
  const method = METHOD_MAP[route.method];
  if (!method) return ""; // unsupported method
  const matcher = JSON.stringify(route.absolute ?? route.path);
  const headers = renderHeaders(route.responseHeaders);

  // Variant-aware handler: branch on query string when bodies differ by query.
  if (route.variants && route.variants.length > 1) {
    return renderVariantHandler(route, method, matcher, headers, index);
  }

  const responseExpr = renderResponse(route, route.body, route.status, headers);
  return `  http.${method}(${matcher}, () => {\n    return ${responseExpr};\n  })`;
}

function renderVariantHandler(
  route: MockRoute,
  method: string,
  matcher: string,
  headers: string,
  index: number,
): string {
  void index;
  const table = route.variants!
    .map((v) => {
      const resp = renderResponse(route, v.body, v.status, headers);
      return `      [${JSON.stringify(v.query)}]: () => ${resp}`;
    })
    .join(",\n");
  const fallback = renderResponse(route, route.body, route.status, headers);

  return `  http.${method}(${matcher}, ({ request }) => {
    const __q = sauceStableQuery(new URL(request.url));
    const __variants: Record<string, () => Response> = {
${table}
    };
    return (__variants[__q] ?? (() => ${fallback}))();
  })`;
}

function renderResponse(
  route: MockRoute,
  body: string,
  status: number,
  headers: string,
): string {
  const init = `{ status: ${status}, headers: ${headers} }`;

  if (route.bodyEncoding === "base64") {
    return `new HttpResponse(sauceFromBase64(${JSON.stringify(body)}), ${init})`;
  }
  if (body === "") {
    return `new HttpResponse(null, ${init})`;
  }
  if (isJsonContentType(route.contentType)) {
    // Embed parsed JSON when valid, else fall back to a raw text response.
    try {
      const parsed = JSON.parse(body);
      return `HttpResponse.json(${stableStringify(parsed)}, ${init})`;
    } catch {
      /* fall through to text */
    }
  }
  return `HttpResponse.text(${JSON.stringify(body)}, ${init})`;
}

function renderHeaders(headers: Record<string, string>): string {
  // Always keep content-type; pass through the safelisted remainder.
  const entries = Object.entries(headers);
  if (entries.length === 0) return "{}";
  const lines = entries.map(([k, v]) => `${JSON.stringify(k)}: ${JSON.stringify(v)}`);
  return `{ ${lines.join(", ")} }`;
}

/** Deterministic JSON.stringify so generated output is stable across runs. */
function stableStringify(value: unknown): string {
  return JSON.stringify(value, replacer(), 2);
}
function replacer() {
  return (_key: string, val: unknown) => {
    if (val && typeof val === "object" && !Array.isArray(val)) {
      const sorted: Record<string, unknown> = {};
      for (const k of Object.keys(val as Record<string, unknown>).sort()) {
        sorted[k] = (val as Record<string, unknown>)[k];
      }
      return sorted;
    }
    return val;
  };
}

const base64Helper = `
function sauceFromBase64(b64: string): Uint8Array {
  const bin = atob(b64);
  const bytes = new Uint8Array(bin.length);
  for (let i = 0; i < bin.length; i++) bytes[i] = bin.charCodeAt(i);
  return bytes;
}
`;

// Mirrors stableQuery() in src/util/url.ts so variant lookup keys match.
const stableQueryHelper = `
const SAUCE_CACHE_BUSTERS = new Set(["_", "t", "ts", "timestamp", "cachebust", "cb", "v"]);
function sauceStableQuery(url: URL): string {
  return [...url.searchParams.entries()]
    .filter(([k]) => !SAUCE_CACHE_BUSTERS.has(k.toLowerCase()))
    .sort(([a], [b]) => a.localeCompare(b))
    .map(([k, v]) => k + "=" + v)
    .join("&");
}
`;

const bootstrapModule = `/* eslint-disable */
// Generated by sauce-code. Starts the MSW worker in development only.
import { worker } from "./browser";

let __started: Promise<unknown> | undefined;

export function startMocks() {
  if (typeof window === "undefined") return Promise.resolve();
  if (!__started) {
    __started = worker.start({
      onUnhandledRequest: "bypass",
      quiet: false,
    });
  }
  return __started;
}
`;
